In [1]:
import numpy as np
x = np.array([1.0, 2.0, 3.0])
print(x)
type(x)

[1. 2. 3.]


numpy.ndarray

In [4]:
x = np.array([1.0, 2.0, 3.0])
y = np.array([2.0, 4.0, 6.0])
print(x + y) # 对应元素的加法

print(x - y)
print(x * y) # element-wise product
print(x / y)

[3. 6. 9.]
[-1. -2. -3.]
[ 2.  8. 18.]
[0.5 0.5 0.5]


In [6]:
# 广播
x = np.array([1.0, 2.0, 3.0])
print( x / 2.0)

[0.5 1.  1.5]


In [7]:
A = np.array([[1, 2], [3, 4]])
print(A)
print(A.shape)
print(A.dtype)

[[1 2]
 [3 4]]
(2, 2)
int64
